### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by plfiorini** [lirios/website#1]
Make the code testable (mock the data) and write a unit test for the handlers.
- http://www.markjberger.com/testing-web-apps-in-golang/
- https://elithrar.github.io/article/testing-http-handlers-go/

**Comment by zigapk** [comment]
What exactly should it test? I can add sample json (and the json reporting errors) that can currently be retrieved from slack and check the output. Otherwise, I don't see what should be tested.

**Comment by plfiorini** [comment]
@zigapk Now it tests that the handler returns a 200 status code and that the response JSON can be serialized and the Ok field is true. Can't think of any other useful test.
