### ISSUE TITLE
Team API: Missing profile pictures

### ISSUE THREAD

**Issue by plfiorini** [lirios/website#3]
Some members like myself have a profile picture but our services doesn't return it.

**Comment by zigapk** [comment]
I have already done some research about that a few months ago. I am not sure, but as far as I remember it works like that: if user sets his profile picture in slack, slack will serve its url properly. However, if user didn't set his profile pic and slack can obtain it elsewhere (other social networks), slack will show it in conversations, but api will serve some kind of slack default picture.

I already brought this issue up on slack once, but I don't think even I have my profile pic properly set.

**Comment by plfiorini** [comment]
@zigapk yeah exactly what happens. for instance on our profiles there's a gravatar url but that url works if I open it with chrome. The URL is passed a few parameters with GET like s and d, the service then returns it with MISSING so it's not slack that gives us those MISSING URLs.

**Comment by plfiorini** [comment]
http://stackoverflow.com/questions/24661862/url-escaping-producing-amissing-instead-of-3a
