### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by joeblew99** [lirios/website#7]
FYI - its still down for me at least.

https://plus.google.com/+PierLuigiFiorini/posts/c3c9J33PYNT

**Comment by plfiorini** [comment]
It is down again, bummer

**Comment by plfiorini** [comment]
This is awesome, their servers are so slow that I cannot even file a support ticket :/

**Comment by joeblew99** [comment]
geeez - i guess its free ?
i host on google storage. If i need any backend i just use docker on google
cloud.

**Comment by plfiorini** [comment]
No I pay for the hosting and I pay quite a lot of money for the domain.
The problem is not the hosting, but the domain. It's a name resolution issue.

**Comment by plfiorini** [comment]
Now it works again.

**Comment by joeblew99** [comment]
cheers - for me too.

Since your using golang have a look here :)
https://github.com/therecipe/qt/tree/master/internal/examples/3rdparty/fluid

to run it, once you have the environment paths setup as per root readme.md
````
# bootstrap 
go run init.go

demo/qtdeploy
````

Worked first time for me.  I really wanted to try lirios, and found the setup pretty touch.
Using golang, it all just worked...
